FROM postgres:9.6.8-alpine

RUN mkdir -p /docker-entrypoint-initdb.d

COPY docker/db/docker-pg-setup.sh /docker-entrypoint-initdb.d
COPY docker/db/db_start.sh  /docker-entrypoint-initdb.d

RUN chmod 755 /docker-entrypoint-initdb.d/docker-pg-setup.sh
RUN chmod 755 /docker-entrypoint-initdb.d/db_start.sh

EXPOSE 5432
ENTRYPOINT []
CMD /docker-entrypoint-initdb.d/db_start.sh
